"""added columns in durable_step table

Revision ID: 02608bcbe714
Revises: f2aca9f3af29
Create Date: 2026-05-15 13:27:01.824968

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '02608bcbe714'
down_revision: Union[str, Sequence[str], None] = 'f2aca9f3af29'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('durable_steps', sa.Column('paused_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('durable_steps', sa.Column('killed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('durable_steps', sa.Column('resumed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('durable_steps', sa.Column('killed_by', sa.String(), nullable=True))
    op.add_column('durable_steps', sa.Column('resumed_by', sa.String(), nullable=True))
    op.add_column('durable_steps', sa.Column('pause_reason', sa.String(), nullable=True))
    op.add_column('durable_steps', sa.Column('runtime_controlled', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('durable_steps', 'runtime_controlled')
    op.drop_column('durable_steps', 'pause_reason')
    op.drop_column('durable_steps', 'resumed_by')
    op.drop_column('durable_steps', 'killed_by')
    op.drop_column('durable_steps', 'resumed_at')
    op.drop_column('durable_steps', 'killed_at')
    op.drop_column('durable_steps', 'paused_at')
    # ### end Alembic commands ###
