"""modify user  table

Revision ID: 0875777cda3b
Revises: 92b98059be54
Create Date: 2026-05-18 12:59:46.122769

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0875777cda3b'
down_revision: Union[str, Sequence[str], None] = '92b98059be54'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'workspace_id')
    op.drop_column('users', 'role')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('workspace_id', sa.UUID(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
