"""added columns in durable step table

Revision ID: 0c918048e51a
Revises: 75bb62d47c2b
Create Date: 2026-05-09 19:08:51.593699

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c918048e51a'
down_revision: Union[str, Sequence[str], None] = '75bb62d47c2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('durable_steps', sa.Column('cache_hit', sa.Boolean(), nullable=True))
    op.add_column('durable_steps', sa.Column('event_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('durable_steps', 'event_type')
    op.drop_column('durable_steps', 'cache_hit')
    # ### end Alembic commands ###
