"""new tables added 

Revision ID: 0e1e637fbff3
Revises: 906340590038
Create Date: 2026-05-23 15:12:55.727437

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e1e637fbff3'
down_revision: Union[str, Sequence[str], None] = '906340590038'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agent_policies', sa.Column('enable_idempotency', sa.Boolean(), nullable=True))
    op.add_column('agent_policies', sa.Column('enable_budget_control', sa.Boolean(), nullable=True))
    op.add_column('agent_policies', sa.Column('enable_retry_control', sa.Boolean(), nullable=True))
    op.add_column('agent_policies', sa.Column('enable_loop_detection', sa.Boolean(), nullable=True))
    op.add_column('agent_policies', sa.Column('max_execution_time_seconds', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agent_policies', 'max_execution_time_seconds')
    op.drop_column('agent_policies', 'enable_loop_detection')
    op.drop_column('agent_policies', 'enable_retry_control')
    op.drop_column('agent_policies', 'enable_budget_control')
    op.drop_column('agent_policies', 'enable_idempotency')
    # ### end Alembic commands ###
