"""add updated_at in DurableStep table

Revision ID: 1e60e972d49f
Revises: ed285d1634df
Create Date: 2026-05-09 18:33:17.521977

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e60e972d49f'
down_revision: Union[str, Sequence[str], None] = 'ed285d1634df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('durable_steps', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('durable_steps', 'updated_at')
    # ### end Alembic commands ###
