"""add auth

Revision ID: 30db52321d93
Revises: 7c0c878760b5
Create Date: 2026-05-07 21:47:51.850204

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30db52321d93'
down_revision: Union[str, Sequence[str], None] = '7c0c878760b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agents', sa.Column('email', sa.String(), nullable=True))
    op.add_column('agents', sa.Column('password_hash', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'agents', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'agents', type_='unique')
    op.drop_column('agents', 'password_hash')
    op.drop_column('agents', 'email')
    # ### end Alembic commands ###
