"""added column in durable_step table

Revision ID: 3d87a1c74eb9
Revises: 02608bcbe714
Create Date: 2026-05-15 13:43:47.825311

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d87a1c74eb9'
down_revision: Union[str, Sequence[str], None] = '02608bcbe714'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('durable_steps', sa.Column('started_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('durable_steps', 'started_at')
    # ### end Alembic commands ###
