"""add column in agent table

Revision ID: 43684afa29e8
Revises: 177cf937f583
Create Date: 2026-05-16 18:22:54.206946

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43684afa29e8'
down_revision: Union[str, Sequence[str], None] = '177cf937f583'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agents', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('agents', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agents', 'updated_at')
    op.drop_column('agents', 'created_at')
    # ### end Alembic commands ###
