"""fix workspace idempotency

Revision ID: 4bac6627956b
Revises: 0875777cda3b
Create Date: 2026-05-19 15:59:08.059523

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4bac6627956b'
down_revision: Union[str, Sequence[str], None] = '0875777cda3b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('durable_steps_idempotency_key_key'), 'durable_steps', type_='unique')
    op.create_unique_constraint('uq_workspace_idempotency', 'durable_steps', ['workspace_id', 'idempotency_key'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_workspace_idempotency', 'durable_steps', type_='unique')
    op.create_unique_constraint(op.f('durable_steps_idempotency_key_key'), 'durable_steps', ['idempotency_key'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
