"""added columns in Usage table

Revision ID: 75bb62d47c2b
Revises: 1e60e972d49f
Create Date: 2026-05-09 18:54:25.129216

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75bb62d47c2b'
down_revision: Union[str, Sequence[str], None] = '1e60e972d49f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usage', sa.Column('prompt_tokens', sa.Integer(), nullable=True))
    op.add_column('usage', sa.Column('completion_tokens', sa.Integer(), nullable=True))
    op.add_column('usage', sa.Column('usage_events', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usage', 'usage_events')
    op.drop_column('usage', 'completion_tokens')
    op.drop_column('usage', 'prompt_tokens')
    # ### end Alembic commands ###
