"""updated all tables

Revision ID: 930b31820697
Revises: cfb9b753d24c
Create Date: 2026-05-23 15:55:55.978606

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '930b31820697'
down_revision: Union[str, Sequence[str], None] = 'cfb9b753d24c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workspace_usage_limits_workspace_id'), table_name='workspace_usage_limits')
    op.drop_table('workspace_usage_limits')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workspace_usage_limits',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('workspace_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('max_monthly_tokens', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('max_monthly_cost', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('max_agents', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('max_parallel_runs', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('workspace_usage_limits_workspace_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('workspace_usage_limits_pkey'))
    )
    op.create_index(op.f('ix_workspace_usage_limits_workspace_id'), 'workspace_usage_limits', ['workspace_id'], unique=True)
    # ### end Alembic commands ###
