"""add user table and modifying agent table

Revision ID: 97dea596b4ee
Revises: 30db52321d93
Create Date: 2026-05-07 22:03:05.637269

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97dea596b4ee'
down_revision: Union[str, Sequence[str], None] = '30db52321d93'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.add_column('agents', sa.Column('user_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'agents', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'agents', type_='foreignkey')
    op.drop_column('agents', 'user_id')
    op.drop_table('users')
    # ### end Alembic commands ###
