"""added workspace table

Revision ID: 9e92da0f14ca
Revises: 41527aef49b0
Create Date: 2026-05-15 16:25:38.462909

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e92da0f14ca'
down_revision: Union[str, Sequence[str], None] = '41527aef49b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workspaces',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('agents', sa.Column('workspace_id', sa.UUID(), nullable=True))
    op.add_column('durable_steps', sa.Column('workspace_id', sa.UUID(), nullable=True))
    op.add_column('usage', sa.Column('workspace_id', sa.UUID(), nullable=True))
    op.add_column('users', sa.Column('workspace_id', sa.UUID(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'workspace_id')
    op.drop_column('usage', 'workspace_id')
    op.drop_column('durable_steps', 'workspace_id')
    op.drop_column('agents', 'workspace_id')
    op.drop_table('workspaces')
    # ### end Alembic commands ###
