"""added columns in Agent table

Revision ID: a37b66f187bd
Revises: 0c918048e51a
Create Date: 2026-05-10 20:32:13.372212

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a37b66f187bd'
down_revision: Union[str, Sequence[str], None] = '0c918048e51a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agents', sa.Column('max_steps', sa.Integer(), nullable=True))
    op.add_column('agents', sa.Column('max_retries', sa.Integer(), nullable=True))
    op.add_column('agents', sa.Column('max_cost', sa.Float(), nullable=True))
    op.add_column('agents', sa.Column('max_repeated_tasks', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agents', 'max_repeated_tasks')
    op.drop_column('agents', 'max_cost')
    op.drop_column('agents', 'max_retries')
    op.drop_column('agents', 'max_steps')
    # ### end Alembic commands ###
