"""add cost to usage table

Revision ID: bd17092ecd5c
Revises: d1406599b293
Create Date: 2026-05-09 16:47:26.953292

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd17092ecd5c'
down_revision: Union[str, Sequence[str], None] = 'd1406599b293'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usage', sa.Column('cost', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usage', 'cost')
    # ### end Alembic commands ###
