"""delete email password column from agent

Revision ID: d1406599b293
Revises: 97dea596b4ee
Create Date: 2026-05-07 22:12:02.017381

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1406599b293'
down_revision: Union[str, Sequence[str], None] = '97dea596b4ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('agents_email_key'), 'agents', type_='unique')
    op.drop_column('agents', 'email')
    op.drop_column('agents', 'password_hash')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agents', sa.Column('password_hash', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('agents', sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_unique_constraint(op.f('agents_email_key'), 'agents', ['email'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
