"""add created_at in DurableStep table

Revision ID: ed285d1634df
Revises: bd17092ecd5c
Create Date: 2026-05-09 18:29:48.453051

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed285d1634df'
down_revision: Union[str, Sequence[str], None] = 'bd17092ecd5c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('durable_steps', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('durable_steps', 'created_at')
    # ### end Alembic commands ###
