"""added columns in Agent table

Revision ID: f2aca9f3af29
Revises: a37b66f187bd
Create Date: 2026-05-11 12:40:34.699468

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2aca9f3af29'
down_revision: Union[str, Sequence[str], None] = 'a37b66f187bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agents', sa.Column('is_killed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agents', 'is_killed')
    # ### end Alembic commands ###
