import logging
from typing import List, Dict, Any, Optional
from sqlalchemy.orm import Session
from uuid import UUID

from app.models.document_intelligence.document_signal import DocumentSignal
from app.core.enums.signals import SignalType

logger = logging.getLogger(__name__)

class SignalStore:
    """
    Manages persistence and retrieval operations for the 'document_signals' table,
    serving as the single source of truth for Python Intelligence.
    """

    def __init__(self, db: Session, document_id: UUID, workspace_id: UUID):
        self.db = db
        self.document_id = document_id
        self.workspace_id = workspace_id

    def save_signals(self, processing_session_id: UUID, detector_name: str, signals: List[Dict[str, Any]]) -> int:
        """
        Batch saves structured signals generated by a Python Intelligence detector.
        """
        if not signals:
            return 0

        db_signals = []
        for sig in signals:
            db_signal = DocumentSignal(
                workspace_id=self.workspace_id,
                document_id=self.document_id,
                processing_session_id=processing_session_id,
                detector=detector_name,
                signal_type=sig.get("signal_type", SignalType.PARAGRAPH),
                page_number=sig.get("page_number", 1),
                confidence=sig.get("confidence", 1.0),
                content=sig.get("content", ""),
                metadata=sig.get("metadata", {})
            )
            db_signals.append(db_signal)

        try:
            self.db.add_all(db_signals)
            self.db.commit()
            logger.info(f"Successfully stored {len(db_signals)} signals from detector '{detector_name}' for doc {self.document_id}")
            return len(db_signals)
        except Exception as e:
            self.db.rollback()
            logger.error(f"Failed to batch save signals for detector {detector_name}: {e}")
            raise

    def get_signals_by_type(self, signal_type: SignalType) -> List[DocumentSignal]:
        """
        Retrieves all signals of a specific type for this document (e.g., all headings or tables).
        """
        return self.db.query(DocumentSignal).filter(
            DocumentSignal.document_id == self.document_id,
            DocumentSignal.workspace_id == self.workspace_id,
            DocumentSignal.signal_type == signal_type
        ).order_by(DocumentSignal.page_number.asc()).all()

    def get_all_document_signals(self) -> List[DocumentSignal]:
        """
        Retrieves the complete sorted signal stream for downstream consumers 
        like Navigation AI and the Chunk Engine.
        """
        return self.db.query(DocumentSignal).filter(
            DocumentSignal.document_id == self.document_id,
            DocumentSignal.workspace_id == self.workspace_id
        ).order_by(DocumentSignal.page_number.asc(), DocumentSignal.id.asc()).all()